//! Embedded Module Signing Keys for NexaOS
//!
//! This module loads the built-in signing keys from `certs/embedded_key.rs`
//! into the kernel's trusted keyring during initialization.
//!
//! Keys are automatically generated by `scripts/sign-module.sh --generate-key`
//! and embedded at compile time via `include!()`.

// Include the auto-generated key data from certs/embedded_key.rs
include!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/certs/embedded_key.rs"
));

/// Initialize embedded signing keys
///
/// This function loads all built-in signing keys into the trusted keyring.
/// It should be called during kmod subsystem initialization.
///
/// # Returns
///
/// The number of keys successfully loaded.
pub fn init() -> usize {
    let mut loaded = 0;

    // Load the primary embedded signing key
    let key_id = &KEY_FINGERPRINT[..core::cmp::min(32, KEY_FINGERPRINT.len())];

    if super::crypto::add_trusted_key(key_id, RSA_MODULUS, RSA_EXPONENT) {
        loaded += 1;
        crate::kinfo!(
            "Loaded embedded signing key: {:02X}{:02X}{:02X}{:02X}...",
            KEY_FINGERPRINT[0],
            KEY_FINGERPRINT[1],
            KEY_FINGERPRINT[2],
            KEY_FINGERPRINT[3]
        );
    } else {
        crate::kwarn!("Failed to load embedded signing key");
    }

    loaded
}
