export default {
  title: 'NexaOS Documentation',
  subtitle: 'API Reference and Developer Documentation',
  generated: 'Generated',
  search: 'Search documentation...',
  categories: {
    all: 'All',
    core: 'Core',
    drivers: 'Drivers',
    userspace: 'Userspace',
    tools: 'Tools'
  },
  noResults: 'No documentation found',
  openDocs: 'Open',
  theme: {
    light: 'Switch to light theme',
    dark: 'Switch to dark theme'
  },
  footer: {
    generated: 'Generated by NexaOS Development Kit (NDK)',
    command: './ndk doc'
  },
  workspace: {
    kernel: 'Kernel - Core OS kernel with scheduler, memory management, and syscalls',
    nvm: 'NVM - Enterprise hypervisor platform with VT-x/AMD-V support',
    tests: 'Tests - Unit and integration tests for kernel subsystems',
    userspace: 'Userspace - C library, dynamic linker, and user programs',
    modules: 'Modules - Loadable kernel modules (filesystems, drivers)',
    'boot-info': 'Boot Info - Multiboot2/UEFI boot information structures'
  }
};
